--- 
title: "LiDaViR"
subtitle: "An introduction to R. Maybe especially useful for Excel users"
author: "Leonardo Hansa"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook: default
documentclass: book
link-citations: yes
description: "R contents and material for classes. Excel users may be the target."
---

# El enfoque

En el texto se expone una introducción del lenguaje de programación R orientada a un lector caracterizado por dos puntos: 

- Si tiene experiencia en datos, la tiene principalmente trabajando con Excel. 
- Está más interesado en el análisis de datos que en la ciencia de datos. Esta distinción puede dar quebraderos de cabeza, pero la idea es que no se modeliza en estas páginas. Nada. Ni se predice, ni se hace _big data_. Solo se hacen la mayoría de las cosas que se hacen en un trabajo con datos, pero nada de humo. 

Consideraciones: 

- Aunque no lo parezca, en cuanto se pase esta página quedará claro que el texto está en inglés. Algún día lo traduciré, porque estoy cansado de que haya tan poco material de programación en español. Pero ese día aún no ha llegado. 
- En los códigos uso _data frames_ generados a partir de ficheros que no tengo muy claro aún dónde dejarlos publicados. Si se necesitan, el lector puede ponerse en contacto conmigo de la forma que prefiera y se los facilito. 

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```